### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by 52THANOS** [NVlabs/FoundationPose#14]
I’m wondering if this project can be installed on a Windows system. i have problem with  pin==2.7.0 and python -m pip install --quiet --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu118_pyt200/download.html

**Comment by wenbowen123** [comment]
On windows, I'd highly recommend using docker.

**Comment by 52THANOS** [comment]
> On windows, I'd highly recommend using docker.

how to build environment in docker? im confused with bash build_all.sh. i dont know what to do after i buit the docker container

**Comment by 52THANOS** [comment]
> On windows, I'd highly recommend using docker.

it's quiet complex to debug in docker.

**Comment by savidini** [comment]
Hey @52THANOS,

I think it might be even more complex to install all required dependencies in windows. :sweat_smile: 

Regarding your issue:


The command does not work on windows, as it tries to install a linux whee;

**Comment by savidini** [comment]
Hey @52THANOS,

I think it is even more complex to install all the required dependencies in Windows. :sweat_smile: 

Regarding your issue:

```bash
python -m pip install --quiet --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu118_pyt200/download.html
```

This will not work on Windows because it tries to install a wheel that is built for Linux. If you want to install on Windows, you need to install from source, see the [PyTorch3D install documentation](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#building--installing-from-source). (This will probably also be the case for other dependencies as well.)

If using Docker is not an option for you and you can't install Linux on your local machine, I would recommend using one of the many cloud GPU providers. I use [Genesis Cloud](https://www.genesiscloud.com/) for a lot of testing (0.25$/h on a RTX3090). I had no problems running FoundationPose on there, just note #38.

If this is an option for you and you have any questions or problems, please let me know and maybe I can help.
