### ISSUE TITLE
Guidence for Novel objects with model-free approach 

### ISSUE THREAD

**Issue by Kaivalya192** [NVlabs/FoundationPose#142]
Respected Developer,

Till now i have succesfuly run your demo model on my system , as i know the demo of mustard bottle post estimation and tracking needs cad mesh. i want to use model free approach as you mentioned in the res. paper . I have Intel realsense D435i and rtx 4060ti. I have captued reference images (~16) of an object. now how to apply foundation pose on it ... can you guid me through this ?

is it neccesary to create mesh file for novel objects , can we do few shot version for novel objects?

Thank you.

**Comment by wenbowen123** [comment]
Hi, for the reference images, you also need their poses relative to the camera. You can refer to the model-free setup under [here](https://github.com/NVlabs/FoundationPose?tab=readme-ov-file#run-on-public-datasets-linemod-ycb-video)

**Comment by Kaivalya192** [comment]
How can i track pose for video captured (novel object)of any object by my depth camera ...
Requirments:-RGBD image sequence, first masked frame , some reference images?

**Comment by wenbowen123** [comment]
1)To train nerf, check this (https://github.com/NVlabs/FoundationPose/blob/main/bundlesdf/run_nerf.py). See more instructions in readme.
2)yes, it's better to follow the data format so that you can plug and play
3)This is on you. One option is to use [bundleSDF ](https://github.com/NVlabs/BundleSDF)to reconstruct mesh automatically
