### ISSUE TITLE
Evaluation result on lmo

### ISSUE THREAD

**Issue by angang0512** [NVlabs/FoundationPose#218]
Hi,
Thank you for the great work! I am trying to reproduce you result and I have run the run_linemod.py locally and evaluate the result on Bop server, However, it shows a better result than you official submission, (AR: 0.817), is this expected? did you update your model after the Bop submission?

**Comment by wenbowen123** [comment]
Hi, there could be some randomness in each run. The numbers we reported are just one of them. So it maybe possible that you got better results. Thanks for sharing!

**Comment by henry1-0** [comment]
> 嗨， 谢谢你的出色工作！我正在尝试重现你的结果，我已经在本地运行了 run_linemod.py 并在 Bop 服务器上评估了结果，但是，它显示的结果比你官方提交的结果要好（AR：0.817），这是预期的结果吗？你在 Bop 提交后更新了你的模型吗？

Hello, I would like to ask you how you simplified the code when running the LM dataset so that the output can be simplified to only show the results of the loop. 
![8](https://github.com/user-attachments/assets/7816a2cb-31c6-4b7b-abed-ebf7c9479e2a)
The picture shows some of the results after I ran it. I want to simplify it. How should I do it? Thank you.

**Comment by tungyen** [comment]
@henry1-0 Could I ask where did you download the LINEMOD and YCB_Video dataset? I could not find a correct one for FoundationPose. Thank you!

**Comment by wenbowen123** [comment]
you can download those data from BOP website.
